server:
  port: 8081

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sns:
        region: ${AWS_SNS_REGION}

letter-sender:
    aws:
      sns:
        topic-arn: ${AWS_SNS_TOPIC_ARN}
